spring:
  application:
    name:  eureka-server
server:
  port: 7000
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:7000/eureka/
    fetch-registry: false
    register-with-eureka: false